# numpy joining Array

# Case:1 concate 1D array

In [3]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


# Case:2 concate 2D array

# c-I:axis=0: 

In [5]:
b1=np.array([[1,2],[3,4]])
b2=np.array([[5,6],[7,8]])
b3=np.concatenate((b1,b2),axis=0)
print(b3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [8]:
b1


array([[1, 2],
       [3, 4]])

In [9]:
b2

array([[5, 6],
       [7, 8]])

# c-II: axis=1:

In [13]:
b11=np.array([[1,2],[3,4]])
b21=np.array([[5,6],[7,8]])
b31=np.concatenate((b1,b2),axis=1)
print(b31)          # 0 aetale row and  aetale column

[[1 2 5 6]
 [3 4 7 8]]


# numpy spliting array

# case-1 splitting 1D array



In [22]:
D=np.array([1,2,3,4,5,6])
D1=np.array_split(D,3)
D2=np.array_split(D,2)
D3=np.array_split(D,4)
D4=np.array_split(D,6)
D5=np.array_split(D,7)

print(D1)
print(D2)
print(D3)
print(D4)
print(D5)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32)]


# case-2 splitting 2D array

In [25]:
B=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
B1=np.array_split(B,3)
B2=np.array_split(B,4)
print(B1)
print(B2)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


In [28]:
B=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
B1=np.array_split(B,3,axis=1)
B2=np.array_split(B,4,axis=1)
print(B1)
print(B2)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32)]
[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32), array([], shape=(6, 0), dtype=int32)]


# Where Function:

In [33]:
# where fun index nu. return kare che
E=np.array([1,2,3,4,5,6,4,7,4])
x=np.where(E==4)     # jya jya 4 aave tya no index nu. return kare
print(x)
x1=np.where(E%2==1) 
print(x1)                 #3 index nu. return kare ch samjaje
x2=np.where(E%3==0) 
print(x2)   

(array([3, 6, 8], dtype=int64),)
(array([0, 2, 4, 7], dtype=int64),)
(array([2, 5], dtype=int64),)


# numpy sorting array

case-Isorting 1D array:

In [34]:
A=np.array([3,2,1,0])
print(np.sort(A))


[0 1 2 3]


# case-IIsorting 2D array:

In [39]:
B=np.array([[3,2,1,0],[4,6,8,2]])
print(np.sort(B))


[[0 1 2 3]
 [2 4 6 8]]


# case-III sorting 3D array:

In [43]:
B=np.array([[[3,2,1,0],[4,6,8,2]],[[8,6,7,5],[8,6,2,4]]])
print(np.sort(B))

[[[0 1 2 3]
  [2 4 6 8]]

 [[5 6 7 8]
  [2 4 6 8]]]


# Decending Order:

In [46]:
A=np.array([3,2,1,0])
print(np.sort(A)[::-1])
B=np.array([[3,2,1,0],[4,6,8,2]])
print(np.sort(B)[::-1,::-1])
c=np.array([[[3,2,1,0],[4,6,8,2]],[[8,6,7,5],[8,6,2,4]]])
print(np.sort(c)[::-1,::-1,::-1])

[3 2 1 0]
[[8 6 4 2]
 [3 2 1 0]]
[[[8 6 4 2]
  [8 7 6 5]]

 [[8 6 4 2]
  [3 2 1 0]]]
