
# Numpy

#  create numpy array

In [3]:
import numpy as np
a=np.array([1,2,3,4,5])
print(type(a))


<class 'numpy.ndarray'>


In [6]:
import numpy as np
a1=np.array((1,2,3,4,5))
print(type(a1))


<class 'numpy.ndarray'>


In [9]:
#1. zero dimantinal array  (0D Array)
a1=np.array(42)
print(a1)
print(type(a1))
a1=np.array([42])
print(a1)
print(type(a1))


42
<class 'numpy.ndarray'>
[42]
<class 'numpy.ndarray'>


In [11]:
#2. 2 dimantinal array  (2D Array)
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)
print(type(a2))
a2=np.array([[1,2,3],[4,5,6],[7,8,9,10]])   # same size hovi joi
print(a2)
print(type(a2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[list([1, 2, 3]) list([4, 5, 6]) list([7, 8, 9, 10])]
<class 'numpy.ndarray'>


<ipython-input-11-752703c5a149>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  a2=np.array([[1,2,3],[4,5,6],[7,8,9,10]])


In [12]:
#3. 3 dimantinal array  (3D Array)
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,20,30]]])
print(a3)
print(type(a3))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 20 30]]]
<class 'numpy.ndarray'>


#  #Check number of dimantion 

In [13]:
a=np.array(42)
b=np.array([42,45,78,96])
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,20,30]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


#  # Higher dimensional array:

In [14]:
A=np.array([1,2,3,4],ndmin=5)  # ndmin karavathi 1d array ne 5d array ma convert kari sakay
print(A)


[[[[[1 2 3 4]]]]]


#  #numpy  array slicing

In [24]:
#1.1D array:
A1=np.array([1,2,3,4,5,6,7,8,9,10])
print(A1[8:10])
print(A1[0:4])
print(A1[:])  # aakho array copy thay
print(A1[::])# aakho array copy thay
print(A1[1:-1]) # pela and chela sivay na badha mate gokhi le
print(A1[-2:-7:-2]) # revers ma 1-1 step mukine print karavava mate

[ 9 10]
[1 2 3 4]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[2 3 4 5 6 7 8 9]
[9 7 5]


In [33]:
#2. 2D array:
B=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(B[:,0:2])   # darek na pela be leva mate
print(B[1:,3:])   # bija be na chela be mate
print(B[::2,1::2]) # print pela and chela na ek ek muki ne 
print(B[-1:-3:-1,-2::-2])   # chela be na last second thi ek-ek mukine
print(B[-1:-3:-1,-2:-5:-2])   # chela be na last second thi ek-ek mukine
print("pela and chela ma reverse ma 3,2 and 13,12 mate")
print(B[::2,-3:-5:-1])
print("pela and chela ma positive index thi 3,2 and 13,12 mate")
print(B[::2,2:0:-1])


[[ 1  2]
 [ 6  7]
 [11 12]]
[[ 9 10]
 [14 15]]
[[ 2  4]
 [12 14]]
[[14 12]
 [ 9  7]]
[[14 12]
 [ 9  7]]
pela and chela ma reverse ma 3,2 and 13,12 mate
[[ 3  2]
 [13 12]]
pela and chela ma positive index thi 3,2 and 13,12 mate
[[ 3  2]
 [13 12]]


In [41]:
#3  3D array
C=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print("6,12 and 18 mate , ")
print(C[:,1:,2:])
print("6,12,18 indexing thi kidhu hoy tyare")
print(C[:,1,2])
print("17,16 11,10 mate")
print(C[-1:-3:-1,1:,-2::-1])
print("11,10 17,16 mate")
print(C[1:3:1,1:,-2::-1])
print("10,11 16,17 mate")
print(C[1:3:1,1:,0:2:])

6,12 and 18 mate , 
[[[ 6]]

 [[12]]

 [[18]]]
6,12,18 indexing thi kidhu hoy tyare
[ 6 12 18]
17,16 11,10 mate
[[[17 16]]

 [[11 10]]]
11,10 17,16 mate
[[[11 10]]

 [[17 16]]]
10,11 16,17 mate
[[[10 11]]

 [[16 17]]]


# Numpy array Shape:

In [44]:
# shape no ans hamesa tuple ma j hoy 
D=np.array([[1,2,3,4],[5,6,7,8]])
print(D)
print(D.shape)
# zero D sudhi nu jose yad raakhaje

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [45]:
D=np.array([[[1,2,3,4,5],[5,6,7,8,9]]])
print(D)
print(D.shape)


[[[1 2 3 4 5]
  [5 6 7 8 9]]]
(1, 2, 5)


In [47]:
D=np.array([[[[1,2],[4,5],[5,6],[8,9]]]])
print(D)
print(D.shape)


[[[[1 2]
   [4 5]
   [5 6]
   [8 9]]]]
(1, 1, 4, 2)


# Numpy Array reshapeing:

# 
# CASE-1: reshape from 1D to 2D:


In [52]:
F=np.array([1,2,3,4,5,6,7,8,9,10,11,12])  # jetali sankhya hoy aetali ne be sankhya na gunakar thi aa sankhya mali javi joi
F1=F.reshape(2,6)
#F2=F.reshape(2,6)    Error aavase
F3=F.reshape(3,4)
F4=F.reshape(6,2)
F5=F.reshape(4,3)
F6=F.reshape(1,12)
F7=F.reshape(12,1)
print(F1)
print(F3)
print(F4)
print(F5)
print(F6)
print(F7)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


# CASE-2 Reashape from 1D to 3D:

In [56]:
W=np.array([1,2,3,4,5,6,7,8,9,10,11,12])  # jetali sankhya hoy aetali ne be sankhya na gunakar thi aa sankhya mali javi joi
W1=W.reshape(2,2,3)
print(W1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Unknown dimantation:

In [59]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x1=x.reshape(2,2,-1)  # unkown dimantation hoy tya -1 lakhi devu e jate baki nu kam kari dese.
print(x1)
#x2=x.reshape(-1,2,4)    Error aavase overall gunakar x jetalo thao javo joi nakar error aapase

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Flattening the Array: 

In [61]:
# koi pan array ne 1D ma convert karava mate aano use thay:
FF=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
FF1=x.reshape(-1)  # reshape na brecket ma khali -1 lakhi devu.
print(FF1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Numpy Array iterating:

# Case-1 Iterating 1D array:

In [62]:
Q=np.array([1,2,3])  # baki 
for i in Q:
    

SyntaxError: unexpected EOF while parsing (<ipython-input-62-ed7d6dd83536>, line 3)

# Case-2 Iterating 2D Array:

In [63]:
R=np.array

# Case-3 Iterating 3D Array:

In [64]:
T=np.array([[[1,2],[4,5]],[7,8]])

<ipython-input-64-742c36c2a853>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  T=np.array([[[1,2],[4,5]],[7,8]])


75


In [68]:
from numpy import random
x=random.randint(100)
print(x)      # 0-100 vache ni random value select kari ne apase
x1=random.randint(50,100)
print(x1) 


10
59


In [72]:
y=random.rand()  # 0-1 vache ni koi value return karase
print(y)
y1=random.rand(5)  # 0-1 vache ni koi pan 5 value return karase as array
print(y1)
x2=random.randint(1,51,size=(5))  # 5 value lese and array ma aapase
print(x2) 
x3=random.randint(1,51,size=(3,5)) 
print(x3) 


0.7475661455629383
[0.38544672 0.14317229 0.84492888 0.49970517 0.47716948]
[29 41 18 35 18]
[[33 48 24 39  8]
 [19 23  4 22 36]
 [47  9 50 21 14]]


In [73]:
z=random.choice([3,3,4,56,7,5])
print(z)

4


In [74]:
# wpp for number gusening game
# wapp for number guessing game
b = random.randint(100)
attempt = 5
while attempt>0:
    a = int(input("Guess the number: "))
    if a==b:
        print("Correct")
        break
    else:
        attempt -= 1
        print("Incorrect")
    if a>b:
        print("High")
    if a<b:
        print("Low")
if attempt == 0:
    print(b,"Correct value")

Guess the number: 50
Incorrect
Low
Guess the number: 70
Incorrect
High
Guess the number: 60
Incorrect
High
Guess the number: 55
Incorrect
High
Guess the number: 53
Incorrect
High
51 Correct value
